name: Cypress Tests for Helpdesk API

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Executa diariamente às 2:00 AM UTC
    - cron: "0 2 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Setup Helpdesk API
        run: |
          # Clone e setup da API
          git clone https://github.com/automacaohml/helpdesk-api.git api
          cd api
          npm install
          # Inicia API em background
          npm start &
          sleep 10
          # Verifica se API está rodando
          curl -f http://localhost:3000/users || exit 1

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          config: video=true,screenshotOnRunFailure=true
        env:
          CYPRESS_baseUrl: http://localhost:3000

      - name: Gerar relatórios
        if: always()
        run: |
          npm run report:merge
          npm run report:generate

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results-${{ matrix.browser }}
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/reports/
          retention-days: 7

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress Tests (${{ matrix.browser }})
          path: cypress/reports/*.json
          reporter: mochawesome-json

  api-validation:
    runs-on: ubuntu-latest
    needs: cypress-run

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar estrutura da API
        run: |
          echo "✅ Testes de API completados com sucesso"
          echo "📊 Relatórios disponíveis nos artifacts"
          echo "🔍 Verifique os resultados detalhados nos artifacts do job"
